export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const DISPLAY_ERROR_MESSAGE = "DISPLAY_ERROR_MESSAGE";
export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR_MESSAGE";

export const RELOAD_API_CALL = "RELOAD_API_CALL";
export const RESET_API_COUNT = "RESET_API_COUNT";

export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";

export const CREATE_LONGRICH_ACCCOUNT_SUCCESS = "CREATE_LONGRICH_ACCCOUNT_SUCCESS";
export const CREATE_LONGRICH_ACCCOUNT_ERROR = "CREATE_LONGRICH_ACCCOUNT_ERROR";
export const GET_LONGRICH_ACCOUNTS_SUCCESS = "GET_LONGRICH_ACCOUNTS_SUCCESS";

export const GET_PLACEMENTS_SUCCESS = "GET_PLACEMENTS_SUCCESS";
export const SELECT_PLACEMENT = "SELECT_PLACEMENT";
export const REMOVE_SELECTED_PLACEMENT = "REMOVE_SELECTED_PLACEMENT";
export const RESET_PLACEMENT_SUGGESTIONS = "RESET_PLACEMENT_SUGGESTIONS";

export const SET_PRODUCT_DISPLAY_VIEW = "SET_PRODUCT_DISPLAY_VIEW";

export const GET_REPO_CONTENT_SUCCESS = "GET_REPO_CONTENT_SUCCESS";
export const LOAD_REPO_CONTENT = "LOAD_REPO_CONTENT";
export const UPDATE_REPO_FOLDER_DIRECTORY = "UPDATE_REPO_FOLDER_DIRECTORY";
export const UPDATE_TO_PREV_FOLDER_DIRECTORY = "UPDATE_TO_PREV_FOLDER_DIRECTORY";
export const SET_REPO_SETTINGS = "SET_REPO_SETTINGS";
export const TOGGLE_SELECT_REPO_FILE = "TOGGLE_SELECT_REPO_FILE";
export const SELECT_REPO_FILE_IN_FOCUS = "SELECT_REPO_FILE_IN_FOCUS";
export const SET_MAIN_REPO_COMPONENT = "SET_MAIN_REPO_COMPONENT";
export const TOGGLE_CREATE_REPO_FOLDER_DISPLAY = "TOGGLE_CREATE_REPO_FOLDER_DISPLAY";
export const TOGGLE_UPLOAD_FILE_DISPLAY = "TOGGLE_UPLOAD_FILE_DISPLAY";


