export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const DISPLAY_ERROR_MESSAGE = "DISPLAY_ERROR_MESSAGE";
export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR_MESSAGE";

export const RELOAD_API_CALL = "RELOAD_API_CALL";
export const RESET_API_COUNT = "RESET_API_COUNT";

export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";

export const CREATE_LONGRICH_ACCCOUNT_SUCCESS = "CREATE_LONGRICH_ACCCOUNT_SUCCESS";
export const CREATE_LONGRICH_ACCCOUNT_ERROR = "CREATE_LONGRICH_ACCCOUNT_ERROR";

export const GET_PLACEMENTS_SUCCESS = "GET_PLACEMENTS_SUCCESS";
export const SELECT_PLACEMENT = "SELECT_PLACEMENT";
export const REMOVE_SELECTED_PLACEMENT = "REMOVE_SELECTED_PLACEMENT";
export const RESET_PLACEMENT_SUGGESTIONS = "RESET_PLACEMENT_SUGGESTIONS";
